/* Generated by Yosys 0.46 (git sha1 e97731b9d, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module Encoder(vdd, vss, Comp, Samp, clk, Dout, eoc);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  input [6:0] Comp;
  wire [6:0] Comp;
  output [2:0] Dout;
  wire [2:0] Dout;
  input Samp;
  wire Samp;
  input clk;
  wire clk;
  output eoc;
  wire eoc;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  sky130_fd_sc_hd__inv_2 _14_ (
    .A(Samp),
    .Y(_00_)
  );
  sky130_fd_sc_hd__and4_2 _15_ (
    .A(Comp[3]),
    .B(Comp[2]),
    .C(Comp[1]),
    .D(Comp[0]),
    .X(_04_)
  );
  sky130_fd_sc_hd__and3_2 _16_ (
    .A(Comp[5]),
    .B(Comp[4]),
    .C(_04_),
    .X(_05_)
  );
  sky130_fd_sc_hd__nor2_2 _17_ (
    .A(Comp[6]),
    .B(Comp[5]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__and2_2 _18_ (
    .A(_04_),
    .B(_06_),
    .X(_07_)
  );
  sky130_fd_sc_hd__o21a_2 _19_ (
    .A1(_05_),
    .A2(_07_),
    .B1(_00_),
    .X(_01_)
  );
  sky130_fd_sc_hd__nor2_2 _20_ (
    .A(Comp[3]),
    .B(Comp[4]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__and4_2 _21_ (
    .A(Comp[1]),
    .B(Comp[0]),
    .C(_06_),
    .D(_08_),
    .X(_09_)
  );
  sky130_fd_sc_hd__o21a_2 _22_ (
    .A1(_05_),
    .A2(_09_),
    .B1(_00_),
    .X(_02_)
  );
  sky130_fd_sc_hd__xnor2_2 _23_ (
    .A(Comp[2]),
    .B(Comp[1]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__and4_2 _24_ (
    .A(Comp[0]),
    .B(_06_),
    .C(_08_),
    .D(_10_),
    .X(_11_)
  );
  sky130_fd_sc_hd__and2_2 _25_ (
    .A(Comp[6]),
    .B(Comp[5]),
    .X(_12_)
  );
  sky130_fd_sc_hd__o211a_2 _26_ (
    .A1(_06_),
    .A2(_12_),
    .B1(Comp[4]),
    .C1(_04_),
    .X(_13_)
  );
  sky130_fd_sc_hd__o21a_2 _27_ (
    .A1(_11_),
    .A2(_13_),
    .B1(_00_),
    .X(_03_)
  );
  sky130_fd_sc_hd__dfxtp_2 _28_ (
    .CLK(clk),
    .D(_00_),
    .Q(eoc)
  );
  sky130_fd_sc_hd__dfxtp_2 _29_ (
    .CLK(clk),
    .D(_01_),
    .Q(Dout[2])
  );
  sky130_fd_sc_hd__dfxtp_2 _30_ (
    .CLK(clk),
    .D(_02_),
    .Q(Dout[1])
  );
  sky130_fd_sc_hd__dfxtp_2 _31_ (
    .CLK(clk),
    .D(_03_),
    .Q(Dout[0])
  );
endmodule
